# Here i will write the configuration related to data ingestion and using this file i will download the data
# from the specified github url

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# artifacts_root: artifacts: This line specifies the root directory for storing artifacts. 
# Artifacts are typically the output files, data, or other results generated during the data ingestion process. 
# In this case, all artifacts will be stored under the "artifacts" directory.

# data_ingestion: This section seems to define the configuration for the data ingestion process.

# root_dir: artifacts/data_ingestion: This line specifies the root directory for the data ingestion process. 
# All files and data related to this specific data ingestion task will be stored under 
# the "artifacts/data_ingestion" directory.

# source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip: 
# This line provides the URL from which the data will be downloaded. 
# The data is located in a ZIP file named "Chicken-fecal-images.zip" and can be
#  found at the provided GitHub URL.

# local_data_file: artifacts/data_ingestion/data.zip: This line specifies the local file path where the 
# downloaded data will be saved. In this case, the downloaded ZIP file will be saved as "data.zip" in the
#  "artifacts/data_ingestion" directory.

# unzip_dir: artifacts/data_ingestion: This line specifies the directory where the downloaded ZIP file 
# will be extracted. In this case, the contents of "data.zip" will be extracted into 
# the "artifacts/data_ingestion" directory.



prepare_base_model:
  root_dir : artifacts/prepare_base_model
  base_model_path : artifacts/prepare_base_model/base_model.h5 
  # Saving base model as an .h5 file
  updated_base_model_path : artifacts/prepare_base_model/updated_base_model.h5
# i will add custom layer ay last of vgg16 model and save it as an updated_base_model.h5
